import routesData from './site-routes.json'

/**
 * Everything search engines are told about the site, in one place.
 *
 * The route table lives in `site-routes.json` rather than here because
 * `scripts/generate-sitemap.mjs` reads the same file at build time. Two lists
 * would drift; one cannot.
 *
 * The host matters. taptest.in redirects to www.taptest.in, so every absolute
 * URL we hand a crawler — canonical, og:url, sitemap, structured data — has to
 * be the www form, or each one is a redirect Google has to follow and
 * reconcile.
 */

export interface RouteMeta {
  /** Always a leading slash, never a trailing one (except the homepage). */
  path: string
  title: string
  description: string
  /** False puts `noindex` on the page. */
  index: boolean
  /** False keeps it out of sitemap.xml; `index` is decided separately. */
  sitemap: boolean
  changefreq?: string
  priority?: string
  /** Files whose last commit dates the page, for sitemap `lastmod`. */
  sources: string[]
}

const data = routesData as {
  siteUrl: string
  siteName: string
  routes: RouteMeta[]
}

export const SITE_URL = data.siteUrl
export const SITE_NAME = data.siteName
export const ROUTES = data.routes

/** 1200x630, generated by `scripts/build-og-image.mjs`. */
export const OG_IMAGE = `${SITE_URL}/assets/og-image.png`
export const OG_IMAGE_WIDTH = 1200
export const OG_IMAGE_HEIGHT = 630

/** The logo Google may show beside the site name. */
export const LOGO_URL = `${SITE_URL}/assets/logounpress.png`

export const CONTACT_EMAIL = 'taptest321@gmail.com'

/**
 * PLACEHOLDER — fill this in once the profiles exist.
 *
 * `sameAs` is how Google ties this site to the same brand elsewhere, and it is
 * the strongest lever available for a name as contested as "TapTest" (a
 * Flutter package, a Rust crate, an iOS app, taptest.co, taptest.info and a
 * medical test all answer to it). Add the full https URL of each profile as
 * you create it, one per line:
 *
 *   'https://x.com/<handle>',
 *   'https://www.linkedin.com/company/<slug>',
 *   'https://github.com/<user>/<repo>',
 *   'https://www.reddit.com/user/<handle>',
 *   'https://en.wikipedia.org/wiki/<page>',
 *
 * Deliberately left empty rather than filled with example URLs: a `sameAs`
 * pointing at a profile that does not exist is a claim Google can check and
 * find false. The key is omitted entirely while this is empty.
 */
export const BRAND_PROFILES: string[] = []

/** Absolute URL for a route path, on the canonical host. */
export function absoluteUrl(path: string): string {
  return path === '/' ? `${SITE_URL}/` : `${SITE_URL}${path}`
}

export function findRoute(pathname: string): RouteMeta | undefined {
  // Trailing slashes are normalised away by Vercel, but a client-side
  // navigation can still produce one.
  const clean = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname
  return ROUTES.find((route) => route.path === clean)
}

const ORGANISATION_ID = `${SITE_URL}/#organization`
const WEBSITE_ID = `${SITE_URL}/#website`

function organisation() {
  return {
    '@type': 'Organization',
    '@id': ORGANISATION_ID,
    name: SITE_NAME,
    url: `${SITE_URL}/`,
    email: CONTACT_EMAIL,
    logo: {
      '@type': 'ImageObject',
      url: LOGO_URL,
      width: 1024,
      height: 1024,
    },
    ...(BRAND_PROFILES.length > 0 ? { sameAs: BRAND_PROFILES } : {}),
  }
}

function website() {
  return {
    '@type': 'WebSite',
    '@id': WEBSITE_ID,
    name: SITE_NAME,
    alternateName: ['TapTest Typing Test', 'TapTest Typing Speed Test'],
    url: `${SITE_URL}/`,
    inLanguage: 'en',
    description:
      'A free typing speed test that measures words per minute and accuracy on real English prose.',
    publisher: { '@id': ORGANISATION_ID },
  }
}

function webApplication() {
  return {
    '@type': 'WebApplication',
    '@id': `${SITE_URL}/#webapp`,
    name: SITE_NAME,
    alternateName: 'TapTest Typing Test',
    url: `${SITE_URL}/`,
    applicationCategory: 'EducationalApplication',
    applicationSubCategory: 'Typing Speed Test',
    operatingSystem: 'Web',
    browserRequirements: 'Requires JavaScript.',
    inLanguage: 'en',
    isAccessibleForFree: true,
    description:
      'Type a timed passage of real prose and see your words per minute, characters per minute and accuracy as you go. One, two and five minute tests at three difficulty levels.',
    featureList: [
      'Timed typing tests of 1, 2 or 5 minutes',
      'Three difficulty levels graded by average word length',
      'Live words per minute, characters per minute and accuracy',
      'Race another person on the same passage',
      'Optional account that keeps your test history',
    ],
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'INR',
      availability: 'https://schema.org/InStock',
    },
    publisher: { '@id': ORGANISATION_ID },
    isPartOf: { '@id': WEBSITE_ID },
  }
}

/** Routes that describe the typing test itself, and so carry WebApplication. */
const APP_PATHS = new Set(['/', '/start', '/test', '/race'])

/**
 * One `@graph` per page. Bundling the nodes lets them reference each other by
 * `@id` instead of repeating the organisation on every page.
 */
export function structuredDataFor(path: string): string {
  const graph: object[] = [organisation(), website()]
  if (APP_PATHS.has(path)) graph.push(webApplication())

  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph })
}
